let haveNever = [
    "Never have I ever got a tattoo",
    "Never have I ever done a nude streak in public",
    "Never have I ever stood someone up on a date",
    "Never have I ever had a speeding ticket",
    "Never have I ever ghosted someone",
    "Never have I ever lied to get out of going to work",
    "Never have I ever given a fake name",
    "Never have I ever dumped someone over text",
    "Never have I ever been sick on public transport",
    "Never have I ever lied to someone in this room",
    "Never have I ever texted an ex out of nowhere",
    "Never have I ever lied on a dating app",
    "Never have I ever shoplifted",
    "Never have I ever kissed a friend's sibling",
    "Never have I ever catfished someone",
    "Never have I ever been refused entry to a club",
    "Never have I ever had a holiday romance",
    "Never have I ever used someone else's toothbrush",
    "Never have I ever peed in the shower",
    "Never have I ever stalked an ex's new partner on social media",
    "Never have I ever been thrown out of a bar or club",
    "Never have I ever gone skinny dipping",
    "Never have I ever gone out with a friend's ex",
    "Never have I ever said 'I love you' when I didn't mean it",
    "Never have I ever been mugged",
    "Never have I ever broken a bone",
    "Never have I ever lied about leaving the club early",
    "Never have I ever been sick on my friend/someone else",
    "Never have I ever kissed a celebrity",
    "Never have I ever eaten leftover food from another table at a restaurant",
    "Never have I ever gone on a blind date",
    "Never have I ever stolen anything",
    "Never have I ever been cheated on",
    "Never have I ever dined and dashed",
    "Never have I ever trespassed",
    "Never have I ever spent more than £200 on a night out",
    "Never have I ever DMed a celebrity",
    "Never have I ever paid for a gym class and not attended",
    "Never have I ever caught my parents having sex",
    "Never have I ever been caught by my parents having sex",
    "Never have I ever been to a nudist beach",
    "Never have I ever pulled an all nighter",
    "Never have I ever cheated on a test or exam",
    "Never have I ever pretended to be someone else",
    "Never have I ever ignored someone I knew in public",
    "Never have I ever ruined an item of clothing I borrowed from a friend",
    "Never have I ever hitchhiked a ride",
    "Never have I ever snuck into a festival or club",
    "Never have I ever lied in this game",
    "Never have I ever peed in public",
    "Never have I ever lied about kissing someone",
    "Never have I ever broken the law",
    "Never have I ever fancied someone in this room",
    "Never have I ever got drunkenly locked out of my house",
    "Never have I ever lied to my boss",
    "Never have I ever got a tattoo I regretted",
    "Never have I ever not worn underwear on a night out",
    "Never have I ever looked through my partner\’s phone",
    "Never have I ever edited my selfies",
    "Never have I ever used someone else\’s Netflix account",
    "Never have I ever ghosted someone for something tiny and unimportant",
    "Never have I ever told someone\’s secret",
    "Never have I ever returned something after I'd already worn it",
    "Never have I ever dropped my phone in a toilet",
    "Never have I ever not eaten before a night out to get more drunk",
    "Never have I ever Googled my own name",
    "Never have I ever forgotten where I parked my car",
    "Never have I ever fancied a friend's parent",
    "Never have I ever used a pick up line",
    "Never have I ever cheated on anyone",
    "Never have I ever re-gifted a present I didn\’t want",
    "Never have I ever given a partner an embarrassing pet name",
    "Never have I ever created a fake Instagram",
    "Never have I ever fake-cried to get something",
    "Never have I ever used a fake ID to get into a club",
    "Never have I ever recreated the I'm a Celeb eating trial",
    "Never have I ever forgotten a friend's birthday",
    "Never have I ever skipped class",
    "Never have I ever cooked drunk and burnt the food",
    "Never have I ever played hooky from school or work",
"Never have I ever stolen anything",
"Never have I ever missed a flight",
"Never have I ever drunk-dialed my ex",
"Never have I ever rode a motorcycle",
"Never have I ever lost a bet",
"Never have I ever gotten lost alone in a foreign country",
"Never have I ever bribed someone",
"Never have I ever gone skinny-dipping",
"Never have I ever cheated on someone",
"Never have I ever sang karaoke",
"Never have I ever broken a bone",
"Never have I ever lived alone",
"Never have I ever been on a yacht",
"Never have I ever been on TV",
"Never have I ever been on a blind date",
"Never have I ever lied to law enforcement",
"Never have I ever gotten a tattoo",
"Never have I ever used a fake ID",
"Never have I ever broken up with someone",
"Never have I ever got seriously hungover",
"Never have I ever used someone else\’s toothbrush",
"Never have I ever clogged somebody else\’s toilet",
"Never have I ever fallen asleep in public",
"Never have I ever kissed someone in public",
"Never have I ever fought in public",
"Never have I ever dined and dashed",
"Never have I ever won the lottery",
"Never have I ever had to go to court",
"Never have I ever been to a destination wedding",
"Never have I ever lied to a boss",
"Never have I ever crashed a wedding",
"Never have I ever kissed more than one person in 24 hours",
"Never have I ever pranked someone",
"Never have I ever had a one-night stand",
"Never have I ever regifted a gift",
"Never have I ever trolled someone on social media",
"Never have I ever climbed out of a window",
"Never have I ever driven over a curb",
"Never have I ever laughed so hard I, um, peed my pants as an adult",
"Never have I ever got on the wrong train or bus",
"Never have I ever cursed in a place of worship",
"Never have I ever snooped through someone\’s stuff",
"Never have I ever tried marijuana",
"Never have I ever gone 24 hours without showering",
"Never have I ever had to take a walk of shame",
"Never have I ever gone on a solo vacation",
"Never have I ever gone on a road trip",
"Never have I ever ate an entire pizza by myself",
"Never have I ever saved a life",
"Never have I ever got a tattoo",
"Never have I ever wanted to be on a reality TV show",
"Never have I ever started a fire",
"Never have I ever gotten stopped by airport security",
"Never have I ever gone viral online",
"Never have I ever left gum in a public space",
"Never have I ever slept outdoors for an entire night",
"Never have I ever ran a marathon",
"Never have I ever given/received a lap dance",
"Never have I ever made a speech in front of 100 people or more",
"Never have I ever relieved myself in a public pool",
"Never have I ever lied to my best friend about who I was with",
"Never have I ever been to a Disney park",
"Never have I ever had a threesome",
"Never have I ever left someone on read",
"Never have I ever lied about my age",
"Never have I ever made up a story about someone who wasn\’t real",
"Never have I ever believed something was haunted",
"Never have I ever participated in a protest",
"Never have I ever had sleep paralysis",
"Never have I ever been the alibi for a lying friend",
"Never have I ever pulled an all-nighter",
"Never have I ever role-played",
"Never have I ever regretted an apology",
"Never have I ever pretended I was sick for attention",
"Never have I ever disliked something that I cooked",
"Never have I ever deleted a post on social media because it didn\’t get enough likes",
"Never have I ever spent more than $100 on a top",
"Never have I ever thrown a drink at someone",
"Never have I ever worn someone else\’s underwear",
"Never have I ever traveled to Europe",
"Never have I ever attempted a trendy diet",
"Never have I ever gone to a strip club",
"Never have I ever binged an entire series in one day",
"Never have I ever tried psychedelics",
"Never have I ever met someone famous",
"Never have I ever gone streaking",
"Never have I ever been on a sports team",
"Never have I ever maxed out a credit card",
"Never have I ever been blackout drunk",
"Never have I ever been engaged",
"Never have I ever gotten married",
"Never have I ever donated to a charity",
"Never have I ever pretended to be sick to get out of something",
"Never have I ever stood up a date",
"Never have I ever ghosted someone",
"Never have I ever fallen in love",
"Never have I ever gone skinny dipping",
 "Never have I ever gone on a blind date",
 "Never have I ever creeped an ex on social media",
 "Never have I ever been hungover",
 "Never have I ever kissed my best friend",
"Never have I ever ghosted someone",
 "Never have I ever gotten a speeding ticket",
 "Never have I ever dined and dashed",
 "Never have I ever used a fake ID",
 "Never have I ever had a crush on a teacher",
 "Never have I ever been in love",
 "Never have I ever made out in a public place",
 "Never have I ever gotten into a physical fight",
 "Never have I ever had an alcoholic drink",
  "Never have I ever played spin the bottle",
"Never have I ever snooped through someone's phone",
 "Never have I ever snuck into a movie theater",
 "Never have I ever kissed a friend's ex",
 "Never have I ever told someone 'I love you' without meaning it",
 "Never have I ever been called a player",
 "Never have I ever smoked a cigarette",
 "Never have I ever given a lap dance",
 "Never have I ever gotten a lap dance",
 "Never have I ever cheated on a test",
 "Never have I ever used a dating app",
 "Never have I ever kissed more than one person in 24 hours",
 "Never have I ever cheated on someone",
"Never have I ever been cheated on",
 "Never have I ever sent a racy text to the wrong person",
 "Never have I ever had a negative bank account balance",
 "Never have I ever played strip poker",
 "Never have I ever been arrested",
 "Never have I ever been expelled",
 "Never have I ever stolen anything",
 "Never have I ever gotten a hickey",
 "Never have I ever been fired",
 "Never have I ever made out in a movie theater",
 "Never have I ever dated someone older than me",
"Never have I ever dated someone younger than me",
"Never have I ever broken the law",
 "Never have I ever been to a nude beach",
 "Never have I stood a date up",
 "Never have I ever stayed in a relationship that I really wasn\’t feeling",
 "Never have I ever given someone a fake phone number",
 "Never have I ever lied to someone in this room",
 "Never have I ever broken up with someone over text",
 "Never have I ever had a crush on an SO\’s best friend",
 "Never have I ever shoplifted",
 "Never have I ever seen a ghost",
 "Never have I told a secret I wasn\’t supposed to share",
 "Never have I ever had a friend with benefits",
 "Never have I ever intentionally started a fight between other people",
 "Never have I ever dated more than one person at once",
 "Never have I ever spent money that wasn\’t mine to spend",
 "Never have I ever had a relationship last less than a month",
 "Never have I ever had a relationship last longer than a year",
 "Never have I ever gotten an unexpected piercing",
 "Never have I ever found a dumb excuse to text an ex",
  "Never have I ever fallen in love at first sight",
  "Never have I ever kissed someone I just met",
  "Never have I ever kept a crush secret from people in this room",
 "Never have I ever been in love with someone without them knowing",
  "Never have I ever been in an open relationship",
  "Never have I ever fantasized about getting back with an ex",
 "Never have I ever helped a friend lie by being their alibi",
 "Never have I ever seriously thought about marrying someone",
  "Never have I ever had a totally online relationship",
  "Never have I ever flirted just to get something I wanted",
 "Never have I ever tried guessing someone\’s password",
 "Never have I ever been caught lying",
"Never have I ever had a crush on a friend's sibling",
"Never have I ever eaten a carton of ice cream",
"Never have I ever gone commando",
 "Never have I ever shaved my head",
 "Never have I ever gotten a tattoo",
"Never have I ever broken a bone",
"Never have I ever been to a bachelorette party or bachelor party",
"Never have I ever gotten heated during a family game night",
"Never have I ever met a celebrity",
"Never have I ever had a surprise party thrown for me",
"Never have I ever travelled solo",
"Never have I ever eaten whipped cream straight out of the can",
"Never have I ever auditioned for a reality television show",
 "Never have I ever told my parents I was staying at a friend's house but was really somewhere else",
"Never have I ever been to a psychic",
"Never have I ever lived alone",
"Never have I ever sang karaoke",
 "Never have I ever stayed overnight in the hospital",
 "Never have I ever deleted a post because it didn't get enough likes",
 "Never have I ever stayed up all night",
 "Never have I ever been on a cruise",
"Never have I ever lost a bet",
 "Never have I ever gotten in a car accident",
 "Never have I ever rode a motorcycle",
 "Never have I ever pretended to be sick to get out of school",
 "Never have I ever beaten a video game",
 "Never have I ever cried at school",
 "Never have I ever talked to a family member about my sex life",
 "Never have I ever been to Mexico",
 "Never have I ever eaten caviar",
"Never have I ever used someone else's Netflix password",
"Never have I ever fallen asleep in class",
 "Never have I ever dyed my hair",
 "Never have I ever read an entire book in a day",
 "Never have I ever seen an alligator in real life",
 "Never have I ever re-gifted a gift",
 "Never have I ever sleepwalked",
 "Never have I ever gone snowboarding",
 "Never have I ever been awake for 48 hours (or more) straight",
 "Never have I ever broken up with someone in a way I regret",
 "Never have I ever fainted",
"Never have I ever had a fight with a SO in public",
 "Never have I ever knowingly spread a rumor",
"Never have I ever cried at school",
 "Never have I ever been somewhere I was sure was haunted",
 "Never have I ever cut my own hair",
 "Never have I ever cheated in a card game",
 "Never have I ever screamed during a scary movie",
 "Never have I ever laughed so hard I spit out my drink",
 "Never have I ever been sent to the principal's office",
 "Never have I ever clogged a toilet",
 "Never have I ever toilet-papered someone's house",
 "Never have I ever worn something I took out of my dirty laundry",
"Never have I ever vomited after a roller coaster ride",
"Never have I ever watched an entire television series in a day",
 "Never have I ever said “I love you” to someone by accident",
 "Never have I ever lied while playing this game",
 "Never have I ever Googled myself",
 "Never have I ever had a pet name for an SO",
 "Never have I ever been given a pet name by an SO",
 "Never have I ever had a dirty dream about a super unexpected person",
 "Never have I ever been accused of sharing too much on social media",
"Never have I ever created a fake social media account",
 "Never have I ever run out of gas while driving",
 "Never have I ever gone to a party I wasn\’t invited to",
 "Never have I ever dated someone super annoying only because they\’re cute",
 "Never have I ever lied on a first date",
 "Never have I ever used someone else's toothbrush",
 "Never have I ever pretended to be on the phone",
"Never have I ever enjoyed a smell I\’m supposed to find gross",
"Never have I ever been on TV for an embarrassing reason",
 "Never have I ever gone several days without showering",
 "Never have I ever turned my underwear inside out so I don\’t have to wash it",
 "Never have I ever lied about what I was doing on social media",
 "Never have I ever been told I snore loudly",
"Never have I ever gone on a date with no intention of paying for anything",
"Never have I ever met up with someone from a dating app",
"Never have I ever slept with someone on the first date",
"Never have I ever pretended to get a text to leave a date",
"Never have I ever gone on a date just to make someone else jealous",
"Never have I ever gone on more than one date in one day",
"Never have I ever talked about my ex on a first date",
"Never have I ever dated someone over ten years older",
"Never have I ever dated someone over ten years younger",
"Never have I ever said I'd call but never bothered",
"Never have I ever dated more than one person at once",
"Never have I ever deleted a chat conversation so a date wouldn\’t see it",
"Never have I ever fallen in love on the first date",
"Never have I ever humiliated myself on a date",
"Never have I ever gotten too drunk on the first date"
]